# Numpy & Pandas Assignment

### Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np
import pandas as pd
import sys
from numpy.linalg import det, inv


In [2]:
arr = np.arange(6)
print(arr, arr.dtype)


[0 1 2 3 4 5] int64


### Q2. Given a NumPy array 'arr', check if its data type is float64.

In [3]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
is_float64 = arr.dtype == np.float64
print(is_float64)


True


### Q3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [5]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


### Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [6]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float32)
print(arr, arr.dtype)


[1. 2. 3. 4.] float32


### Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32.

In [7]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr, arr.dtype)


[1.1 2.2 3.3] float32


### Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [8]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

print(array_attributes(np.array([[1, 2], [3, 4]])))


((2, 2), 4, dtype('int64'))


### Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [9]:
def array_dimension(arr):
    return arr.ndim

print(array_dimension(np.array([[1, 2], [3, 4]])))


2


### Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [10]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

print(item_size_info(np.array([1, 2, 3], dtype=np.int32)))


(4, 12)


### Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [11]:
def array_strides(arr):
    return arr.strides

arr = np.array([1.5, 2.6, 3.7])
print(array_strides(arr))


(8,)


### Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [12]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

print(shape_stride_relationship(np.array([[1, 2, 3], [4, 5, 6]])))


((2, 3), (24, 8))


### Q11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.

In [13]:
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


### Q12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.

In [14]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Q13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with that range.

In [15]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))


[1 3 5 7 9]


### Q14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values.

In [16]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))


[0.   0.25 0.5  0.75 1.  ]


### Q15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix.

In [17]:
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Q16. Write a function that takes a Python list and converts it into a NumPy array.

In [18]:
def list_to_array(lst):
    return np.array(lst)

print(list_to_array([1, 2, 3, 4]))


[1 2 3 4]


### Q17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.

In [19]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
view_arr[0] = 99
print("Original:", arr)
print("View:", view_arr)


Original: [99  2  3  4]
View: [99  2  3  4]


### Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [20]:
def concatenate_arrays(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

# Example:
a18 = np.array([[1,2]])
b18 = np.array([[3,4]])
print("18:", concatenate_arrays(a18, b18, axis=0))


18: [[1 2]
 [3 4]]


### Q19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.

In [21]:
# Create two arrays with same number of rows but different columns and concatenate horizontally
A19 = np.array([[1,2],[3,4]])
B19 = np.array([[5],[6]])
horiz19 = np.concatenate((A19, B19), axis=1)
print("19:\n", horiz19)


19:
 [[1 2 5]
 [3 4 6]]


### Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [22]:
def vertical_stack_list(arr_list):
    return np.vstack(arr_list)

print("20:\n", vertical_stack_list([np.array([1,2]), np.array([3,4]), np.array([5,6])]))


20:
 [[1 2]
 [3 4]
 [5 6]]


### Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [23]:
def inclusive_range(start, stop, step=1):
    return np.arange(start, stop+1, step)

print("21:", inclusive_range(1, 10, 2))


21: [1 3 5 7 9]


### Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [24]:
def ten_linspace():
    return np.linspace(0, 1, 10)

print("22:", ten_linspace())


22: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Q23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [25]:
def five_logspace_1_1000():
    return np.logspace(np.log10(1), np.log10(1000), num=5)

print("23:", five_logspace_1_1000())


23: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


### Q24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [26]:
arr24 = np.random.randint(1, 101, size=(5,3))
df24 = pd.DataFrame(arr24, columns=["Col1","Col2","Col3"])
print("24:\n", df24)


24:
    Col1  Col2  Col3
0    15    78    88
1    42    51    35
2    13     4    52
3    71    44     4
4    84    56     9


### Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the DataFrame.

In [27]:
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

# Example:
df25 = pd.DataFrame({"A":[-5,2,-3,10]})
print("25 before:\n", df25)
print("25 after:\n", replace_negatives(df25.copy(), "A"))


25 before:
     A
0  -5
1   2
2  -3
3  10
25 after:
     A
0   0
1   2
2   0
3  10


### Q26. Access the 3rd element from the given NumPy array.

In [28]:
arr26 = np.array([10,20,30,40,50])
third_element = arr26[2]   # index 2
print("26:", third_element)


26: 30


### Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [29]:
arr27 = np.array([[1,2,3],[4,5,6]])
element_1_2 = arr27[1,2]
print("27:", element_1_2)


27: 6


### Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [30]:
arr28 = np.array([3,8,2,10,5,7])
greater_than_5 = arr28[arr28 > 5]
print("28:", greater_than_5)


28: [ 8 10  7]


### Q29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [31]:
arr29 = np.array([1,2,3,4,5,6,7,8,9])
slice_2_to_5 = arr29[2:6]   # stops before 6 -> includes indices 2,3,4,5
print("29:", slice_2_to_5)


29: [3 4 5 6]


### Q30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.

In [32]:
arr2d_30 = np.array([[1,2,3],[4,5,6],[7,8,9]])
sub30 = arr2d_30[0:2, 1:3]   # rows 0-1, cols 1-2
print("30:\n", sub30)


30:
 [[2 3]
 [5 6]]


### Q31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [33]:
def extract_ordered(arr2d, index_pairs):
    # index_pairs is an array-like of shape (k,2) with (row, col) pairs
    idx = np.array(index_pairs)
    return arr2d[idx[:,0], idx[:,1]]

# Example:
arr31 = np.array([[10,11,12],[13,14,15],[16,17,18]])
indices31 = [[0,2],[2,1],[1,0]]
print("31:", extract_ordered(arr31, indices31))


31: [12 17 13]


### Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [34]:
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

print("32:", filter_greater_than(np.array([1,7,5,10,3]), 5))


32: [ 7 10]


### Q33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [35]:
def extract_3d(a3d, i_idx, j_idx, k_idx):
    # i_idx, j_idx, k_idx must be arrays of same shape
    return a3d[i_idx, j_idx, k_idx]

# Example:
a33 = np.arange(2*3*4).reshape(2,3,4)
i33 = np.array([0,1,1])
j33 = np.array([1,0,2])
k33 = np.array([2,1,3])
print("33:", extract_3d(a33, i33, j33, k33))


33: [ 6 13 23]


### Q34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [36]:
def elements_where_two_conditions(arr, cond1, cond2):
    # cond1 and cond2 are callables returning boolean mask vectors
    return arr[np.logical_and(cond1(arr), cond2(arr))]

arr34 = np.array([1,2,3,4,5,6,7,8,9])
print("34:", elements_where_two_conditions(arr34, lambda x: x>2, lambda x: x%2==0))


34: [4 6 8]


### Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [37]:
def extract_by_row_col(arr2d, rows, cols):
    rows = np.array(rows)
    cols = np.array(cols)
    return arr2d[rows, cols]

a35 = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows35 = [0,1,2]
cols35 = [2,1,0]
print("35:", extract_by_row_col(a35, rows35, cols35))


35: [3 5 7]


### Q36. Given an array arr of shape (3,3), add a scalar value of 5 to each element using NumPy broadcasting.

In [38]:
arr36 = np.array([[1,2,3],[4,5,6],[7,8,9]])
result36 = arr36 + 5
print("36:\n", result36)


36:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### Q37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [39]:
arr1 = np.array([[2,3,4]])  # shape (1,3)
arr2 = np.array([[10,11,12,13],
                 [20,21,22,23],
                 [30,31,32,33]])  # shape (3,4)
# multiply arr2 row i by arr1 element i
factors = arr1.reshape(-1)       # shape (3,)
result37 = arr2 * factors[:, None]  # broadcast to (3,4)
print("37:\n", result37)


37:
 [[ 20  22  24  26]
 [ 60  63  66  69]
 [120 124 128 132]]


### Q38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [40]:
arr1 = np.array([[1,2,3,4]])    # (1,4)
arr2 = np.arange(12).reshape(4,3)  # (4,3)
# To add arr1 to each row we must align shapes; transpose arr1 to (4,1) then broadcast
result38 = arr2 + arr1.T
print("38:\n", result38)


38:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


### Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [41]:
arr1 = np.array([[1],[2],[3]])   # (3,1)
arr2 = np.array([[10,20,30]])    # (1,3)
print("39:\n", arr1 + arr2)      # result shape (3,3)


39:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [42]:
def safe_broadcast_multiply(a, b):
    try:
        return a * b
    except ValueError as e:
        return f"Error: incompatible shapes {a.shape} and {b.shape} for broadcasting"

a40 = np.ones((2,3))
b40 = np.ones((2,2))
print("40:", safe_broadcast_multiply(a40, b40))


40: Error: incompatible shapes (2, 3) and (2, 2) for broadcasting


### Q41. Calculate column-wise mean for the given array.

In [43]:
arr41 = np.array([[1,2,3],[4,5,6]])
col_mean41 = arr41.mean(axis=0)
print("41:", col_mean41)


41: [2.5 3.5 4.5]


### 42. Find maximum value in each row of the given array.

In [44]:
arr42 = np.array([[1,2,3],[4,5,6]])
row_max42 = arr42.max(axis=1)
print("42:", row_max42)


42: [3 6]


### Q43. For the given array, find indices of maximum value in each column.

In [45]:
arr43 = np.array([[1,2,3],[4,5,6]])
argmax_cols43 = arr43.argmax(axis=0)
print("43:", argmax_cols43)


43: [1 1 1]


### Q44. For the given array, apply custom function to calculate moving sum along rows.

In [46]:
def moving_sum(a, window=2):
    # compute moving (sliding) sum along each row, produce array with same shape,
    # using np.convolve per row with 'valid' then pad to original length for demonstration
    out = np.zeros_like(a, dtype=float)
    for i in range(a.shape[0]):
        row = a[i].astype(float)
        conv = np.convolve(row, np.ones(window), mode='same')
        out[i] = conv
    return out

arr44 = np.array([[1,2,3,4],[5,6,7,8]])
print("44:\n", moving_sum(arr44, window=2))


44:
 [[ 1.  3.  5.  7.]
 [ 5. 11. 13. 15.]]


### Q45. In the given array, check if all elements in each column are even.

In [47]:
arr45 = np.array([[2,4,6],[3,5,7]])
all_even_per_col45 = np.all(arr45 % 2 == 0, axis=0)
print("45:", all_even_per_col45)


45: [False False False]


### Q46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.

In [48]:
def reshape_to(arr, m, n):
    return arr.reshape(m, n)

print("46:", reshape_to(np.arange(12), 3, 4))


46: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Q47. Create a function that takes a matrix as input and returns the flattened array.

In [49]:
def flatten_matrix(mat):
    return mat.ravel()

print("47:", flatten_matrix(np.array([[1,2,3],[4,5,6]])))


47: [1 2 3 4 5 6]


### Q48. Write a function that concatenates two given arrays along a specified axis.

In [50]:
def concat_two(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

print("48:", concat_two(np.array([[1,2]]), np.array([[3,4]]), axis=1))


48: [[1 2 3 4]]


### Q49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [51]:
def split_array(a, sections_or_indices, axis=0):
    return np.split(a, sections_or_indices, axis=axis)

print("49:", split_array(np.arange(8), 4))  # split into 4 equal subarrays


49: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]


### Q50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [52]:
def insert_then_delete(arr, insert_idx, insert_vals, delete_idx):
    arr_inserted = np.insert(arr, insert_idx, insert_vals)
    arr_deleted = np.delete(arr_inserted, delete_idx)
    return arr_inserted, arr_deleted

orig50 = np.array([1,2,3,4,5])
ins50, del50 = insert_then_delete(orig50, [2,4], [10,11], [1,3])
print("50 inserted:", ins50, "after delete:", del50)


50 inserted: [ 1  2 10  3  4 11  5] after delete: [ 1 10  4 11  5]


### Q51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

In [53]:
arr51_1 = np.random.randint(1, 50, size=10)
arr51_2 = np.arange(1, 11)
print("51:", arr51_1 + arr51_2)


51: [50 21 41 20 38 52 54 17 27 51]


### Q52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

In [54]:
arr52_1 = np.arange(10, 0, -1)
arr52_2 = np.arange(1, 11)
print("52:", arr52_1 - arr52_2)



52: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


### Q53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.

In [55]:
arr53_1 = np.random.randint(1, 10, size=5)
arr53_2 = np.arange(1, 6)
print("53:", arr53_1 * arr53_2)


53: [ 8 12  3 20 30]


### Q54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

In [56]:
arr54_1 = np.arange(2, 12, 2)  # [2,4,6,8,10]
arr54_2 = np.arange(1, 6)      # [1,2,3,4,5]
print("54:", arr54_1 / arr54_2)


54: [2. 2. 2. 2. 2.]


### Q55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

In [57]:
arr55_1 = np.arange(1,6)
arr55_2 = arr55_1[::-1]
print("55:", arr55_1 ** arr55_2)


55: [ 1 16 27 16  5]


### Q56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [58]:
def count_substring_in_array(arr_str, substring):
    return np.char.count(arr_str, substring).sum()

arr56 = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print("56 count 'hello':", count_substring_in_array(arr56, 'hello'))


56 count 'hello': 3


### Q57. Write a function that extracts uppercase characters from a NumPy array of strings.

In [59]:
def extract_uppercase_chars(arr_str):
    return np.array([''.join([ch for ch in s if ch.isupper()]) for s in arr_str])

arr57 = np.array(['Hello','World','OpenAI','GPT'])
print("57:", extract_uppercase_chars(arr57))


57: ['H' 'W' 'OAI' 'GPT']


### Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [60]:
def replace_substring(arr_str, old, new):
    return np.char.replace(arr_str, old, new)

arr58 = np.array(['hello world', 'hello numpy'])
print("58:", replace_substring(arr58, 'hello', 'hi'))


58: ['hi world' 'hi numpy']


### Q59. Write a function that concatenates strings in a NumPy array element-wise.

In [61]:
def concat_elementwise(a, b):
    return np.char.add(a, b)

a59 = np.array(['Hello ', 'Good '])
b59 = np.array(['World', 'Morning'])
print("59:", concat_elementwise(a59, b59))


59: ['Hello World' 'Good Morning']


### Q60. Write a function that finds the length of the longest string in a NumPy array.

In [62]:
def longest_string_len(arr_str):
    lengths = np.vectorize(len)(arr_str)
    return lengths.max()

arr60 = np.array(['apple','banana','grape','pineapple'])
print("60:", longest_string_len(arr60))


60: 9


### Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [63]:
data61 = np.random.randint(1, 1001, size=100)
mean61 = data61.mean()
median61 = np.median(data61)
var61 = data61.var()
std61 = data61.std()
print("61 mean, median, var, std:", mean61, median61, var61, std61)


61 mean, median, var, std: 511.37 548.0 105919.01309999998 325.4520135135132


### Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [64]:
data62 = np.random.uniform(1, 100, size=50)
p25_75 = np.percentile(data62, [25, 75])
print("62 25th, 75th:", p25_75)


62 25th, 75th: [19.92505171 74.70755826]


### Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

In [65]:
x63 = np.random.randn(50)
y63 = 0.5 * x63 + 0.2 * np.random.randn(50)
corr63 = np.corrcoef(x63, y63)[0,1]
print("63 corrcoef:", corr63)


63 corrcoef: 0.9299109909584696


### Q64. Create two matrices and perform matrix multiplication using NumPy's dot function.

In [66]:
A64 = np.array([[1,2,3],[4,5,6]])
B64 = np.array([[7,8],[9,10],[11,12]])
print("64 dot:\n", np.dot(A64, B64))


64 dot:
 [[ 58  64]
 [139 154]]


### Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [67]:
data65 = np.random.randint(10, 1001, size=50)
p10, p50, p90 = np.percentile(data65, [10,50,90])
q1, q3 = np.percentile(data65, [25,75])
print("65 p10,p50,p90,q1,q3:", p10, p50, p90, q1, q3)


65 p10,p50,p90,q1,q3: 113.30000000000001 475.5 911.1 257.75 765.5


### Q66. Create a NumPy array of integers and find the index of a specific element.

In [68]:
arr66 = np.array([5,3,7,1,9])
def find_index(arr, value):
    idx = np.where(arr == value)[0]
    return int(idx[0]) if idx.size else -1

print("66 index of 7:", find_index(arr66, 7))


66 index of 7: 2


### Q67. Generate a random NumPy array and sort it in ascending order.

In [69]:
arr67 = np.random.randint(0, 100, size=10)
arr67_sorted = np.sort(arr67)
print("67 sorted:", arr67_sorted)


67 sorted: [ 4 31 44 45 53 67 75 81 93 94]


### Q68. Filter elements >20 in the given NumPy array.

In [70]:
arr68 = np.array([10,20,30,40,50])
print("68 filtered >20:", arr68[arr68 > 20])


68 filtered >20: [30 40 50]


### Q69. Filter elements which are divisible by 3 from a given NumPy array.

In [71]:
arr69 = np.array([1,2,3,4,5,6,9])
print("69 divisible by 3:", arr69[arr69 % 3 == 0])


69 divisible by 3: [3 6 9]


### Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [73]:
arr70 = np.array([10,20,25,30,45,40])
print("70 between 20 and 40:", arr70[(arr70 >= 20) & (arr70 <= 40)])


70 between 20 and 40: [20 25 30 40]


### Q71. For the given NumPy array, check its byte order using the dtype attribute byteorder.

In [74]:
arr71 = np.array([1,2,3])
print("71 byteorder:", arr71.dtype.byteorder)
# '=' means native, '<' little-endian, '>' big-endian, '|' not applicable


71 byteorder: =


### Q72. For the given NumPy array, perform byte swapping in place using byteswap().

In [75]:
arr72 = np.array([1,256,65536], dtype=np.int32)
arr72.byteswap(inplace=True)
print("72 byteswapped (in-place):", arr72)


72 byteswapped (in-place): [16777216    65536      256]


### Q73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().

In [92]:
import numpy as np

arr73 = np.array([1, 2, 3], dtype=np.int32)
arr73_swapped = arr73.view(arr73.dtype.newbyteorder())
print("73 original:", arr73, "Swapped view:", arr73_swapped)

73 original: [1 2 3] Swapped view: [16777216 33554432 50331648]


### Q74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().

In [91]:
import numpy as np
import sys

def conditional_swap(a):
    if sys.byteorder == 'little':
        return a.view(a.dtype.newbyteorder('>'))
    else:
        return a.view(a.dtype.newbyteorder('<'))

print("74 conditional swap:", conditional_swap(np.array([1, 2, 3], dtype=np.int32)))

74 conditional swap: [16777216 33554432 50331648]


### Q75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.

In [79]:
def needs_swap(a):
    bo = a.dtype.byteorder
    if bo == '=' or bo == '|':  # native or not-applicable
        return False
    # If dtype indicates opposite endianness of system, swap needed
    return (sys.byteorder == 'little' and bo == '>') or (sys.byteorder == 'big' and bo == '<')

arr75 = np.array([1,2,3], dtype=np.dtype('>i4'))  # big-endian dtype
print("75 needs swap?:", needs_swap(arr75))


75 needs swap?: True


### Q76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

In [80]:
arr76 = np.arange(1,11)
copy_arr76 = arr76.copy()
copy_arr76[0] = 999
print("76 original starts:", arr76[:3], "copy starts:", copy_arr76[:3])
# original unaffected


76 original starts: [1 2 3] copy starts: [999   2   3]


### Q77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

In [81]:
matrix77 = np.random.randint(0, 10, (3,3))
view_slice77 = matrix77[0:2, 0:2]   # this is a view
view_slice77[0,0] = -999
print("77 original after modifying view:\n", matrix77)


77 original after modifying view:
 [[-999    4    5]
 [   7    9    8]
 [   7    8    6]]


### Q78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

In [82]:
array78 = np.arange(1,13).reshape(4,3)
view_b78 = array78[1:3, 0:2]   # view
view_b78 += 5                  # in-place broadcast
print("78 original after broadcasting to view:\n", array78)


78 original after broadcasting to view:
 [[ 1  2  3]
 [ 9 10  6]
 [12 13  9]
 [10 11 12]]


### Q79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.

In [83]:
orig79 = np.arange(1,9).reshape(2,4)
reshaped_view79 = orig79.reshape(4,2)
reshaped_view79[0,0] = -777
print("79 original after reshaped view modification:\n", orig79)


79 original after reshaped view modification:
 [[-777    2    3    4]
 [   5    6    7    8]]


### Q80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

In [84]:
data80 = np.random.randint(0, 10, (3,4))
data_copy80 = data80[data80 > 5].copy()  # explicit copy
if data_copy80.size:
    data_copy80[0] = -999
print("80 original (unchanged):\n", data80)


80 original (unchanged):
 [[1 3 8 6]
 [4 7 4 7]
 [8 3 5 7]]


### Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [85]:
A81 = np.array([[1,2],[3,4]])
B81 = np.array([[5,6],[7,8]])
print("81 add:\n", A81 + B81)
print("81 subtract:\n", A81 - B81)


81 add:
 [[ 6  8]
 [10 12]]
81 subtract:
 [[-4 -4]
 [-4 -4]]


### Q82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.

In [86]:
C82 = np.arange(1,7).reshape(3,2)
D82 = np.arange(7,15).reshape(2,4)
print("82 product:\n", np.dot(C82, D82))


82 product:
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


### Q83. Create a matrix E and find its transpose.

In [87]:
E83 = np.array([[1,2,3],[4,5,6]])
print("83 transpose:\n", E83.T)


83 transpose:
 [[1 4]
 [2 5]
 [3 6]]


### Q 84. Generate a square matrix F and compute its determinant.

In [88]:
F84 = np.array([[4.0, 7.0],[2.0,6.0]])
print("84 determinant:", det(F84))


84 determinant: 10.000000000000002


### Q85. Create a square matrix G and find its inverse.

In [89]:
G85 = np.array([[1.0,2.0],[3.0,4.0]])
print("85 inverse:\n", inv(G85))


85 inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
